import Footer from "./components/layout/Footer";
import Header from "./components/layout/Header";

import "./globals.css";
interface MenuProps {
  children: React.ReactNode; // Define el tipo de children
}
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: MenuProps) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
