import Footer from "./components/layout/Footer";
import Header from "./components/layout/Header";
import { AuthProvider } from "./context/AuthContext";

import "./globals.css";
interface MenuProps {
  children: React.ReactNode;
}
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: MenuProps) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Header />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
