POST http://localhost:4000/api/special-dates HTTP/1.1
Content-Type: application/json

{
  "title": "Cita caminar dos horas",
  "date": "2025-01-15T14:00:00.000Z",
  "time": "14:00",
  "notify": true
}

################################################################

GET  http://localhost:4000/api/special-dates HTTP/1.1
Content-Type: application/json

{
  
  "name": "Compra de supermercado",
  "price": 45.99,
  "date": "2025-01-11T00:00:00.000Z",
  "dayOfWeek": "Sábado"
 
}
################################################################

get http://localhost:4000/api/special-dates/6786b843f32343e690c021d3 HTTP/1.1
Content-Type: application/json

{
  "name": "Hast el momento va funcionado",
  "price": 30000,
  "date": "8/12/2023",
  "day": "lunes"
}

################################################################

PUT   http://localhost:4000/api/special-dates/6786b843f32343e690c021d3  HTTP/1.1
Content-Type: application/json

{
  "title": "Cita con medicina interna",
  "date": "2025-01-15T14:00:00.000Z",
  "time": "16:00",
  "notify": true
}

################################################################

delete  http://localhost:4000/api/special-dates/6786b869f32343e690c021d4   HTTP/1.1
Content-Type: application/json

{
  "name": "mercado",
  "price": 30000,
  "date": "8/12/2023",
  "day": "lunes"
}